stages:
  - build
  
Build:
  image: docker:19.03.0
  only:
    - master
  services:
    - docker:19.03.0-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  stage: build
  before_script:
    - docker info
  script:
    - cp $DEVELOPMENT_ENV .env

